In [1]:
import numpy as np

In [2]:
ages = np.array([22, 38, 26, 35, 28, 0, 54, 2, 27, 14])

In [3]:
ages.shape

(10,)

In [4]:
ages[0]

np.int64(22)

In [5]:
ages[2:5]

array([26, 35, 28])

In [6]:
ages.mean()

np.float64(24.6)

In [7]:
print(ages.mean())

24.6

In [8]:
print(ages[2])

26

In [9]:
print(ages[4:8])

[28  0 54  2]

In [10]:
ages_2d = np.array([[22, 38, 26, 35, 28],
                    [0, 54, 2, 27, 14]])

In [11]:
print(ages_2d)

[[22 38 26 35 28]
 [ 0 54  2 27 14]]

In [12]:
ages_2d.shape

(2, 5)

In [13]:
print(ages_2d[0])
print(ages_2d[1])

[22 38 26 35 28]
[ 0 54  2 27 14]

In [14]:
print(ages_2d[0][1])
print(ages_2d[1][1])

38
54

In [15]:
ages_2d.mean()

np.float64(24.6)

In [16]:
print(ages_2d.max())
print(ages_2d.min())

54
0

In [17]:
import pandas as pd

In [18]:
df = pd.read_csv(r"C:\Users\danam\OneDrive\Desktop\ML_journey\datasets\train.csv")

In [19]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [20]:
df.shape

(891, 12)

In [21]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [23]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [24]:
df["Age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [25]:
df["Survived"]

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [26]:
df["Age"].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888     True
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [27]:
df["Age"].isnull().sum()

np.int64(177)

In [28]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [29]:
df["Age"].mean()

np.float64(29.69911764705882)

In [30]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [31]:
df["Age"].isnull().sum()

np.int64(0)

In [32]:
df["Embarked"].mode()[0]

'S'

In [195]:
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

In [33]:
df["Embarked"].isnull().sum()

np.int64(2)

In [34]:
df = df.drop(columns=["Cabin"])

In [35]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='object')

In [36]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       2
dtype: int64

In [39]:
df["Survived"].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [40]:
df.groupby("Sex")["Survived"].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [42]:
df.groupby("Pclass")["Survived"].mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [45]:
df.groupby(["Sex","Pclass"])["Survived"].mean()

Sex     Pclass
female  1         0.968085
        2         0.921053
        3         0.500000
male    1         0.368852
        2         0.157407
        3         0.135447
Name: Survived, dtype: float64

In [50]:
df["AgeGroup"] = pd.cut(df["Age"],
                bins=[0, 12, 17, 60, 80],
                labels=["Child", "Teens",
                        "Adult", "Senior"])

In [53]:
df.groupby("AgeGroup")["Survived"].mean()

C:\Users\danam\AppData\Local\Temp\ipykernel_5560\2602041343.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby("AgeGroup")["Survived"].mean()

AgeGroup
Child     0.579710
Teens     0.477273
Adult     0.365079
Senior    0.227273
Name: Survived, dtype: float64