In [12]:
# ============================================
# PROJECT 3 — E-commerce Customer & Sales Analytics
# Dataset: UCI Online Retail (541,909 transactions)
# Tools: Python, SQLite, Pandas, Matplotlib
# ============================================

# Importing required libraries
import pandas as pd      # for data manipulation and reading SQL results
import sqlite3           # for creating and connecting to SQLite database
import os                # for checking files and folders on computer

print("All libraries imported successfully!")
print("sqlite3 version:", sqlite3.sqlite_version)

All libraries imported successfully!
sqlite3 version: 3.51.0

In [13]:
# ============================================
# STEP 1: Load the raw CSV data into Pandas
# ============================================

# read_csv() loads the file into a DataFrame
# encoding='utf-8-sig' removes the hidden BOM character
# that Excel adds when saving CSV files
df = pd.read_csv(
    r'C:\Users\danam\OneDrive\Desktop\ML_journey\project_03_ecommerce_sql\datasets\online_retail.csv',
    encoding='utf-8-sig'
)

# Check what we loaded
print("Shape:", df.shape)           # (rows, columns)
print("\nColumns:", df.columns.tolist())  # all 8 column names
print("\nFirst 5 rows:")
df.head()                           # preview first 5 rows

Shape: (541909, 8)

Columns: ['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']

First 5 rows:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01/12/2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01/12/2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01/12/2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01/12/2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01/12/2010 08:26,3.39,17850.0,United Kingdom

In [14]:
# ============================================
# STEP 2: Create SQLite Database
# ============================================

# sqlite3.connect() does two things:
# → if ecommerce.db does NOT exist: creates it fresh
# → if ecommerce.db already EXISTS: opens it
# conn = the open connection (door) to the database
conn = sqlite3.connect(
    r'C:\Users\danam\OneDrive\Desktop\ML_journey\project_03_ecommerce_sql\datasets\ecommerce.db'
)

# df.to_sql() moves the entire DataFrame into the database
# 'orders'          → name of the table inside the database
# conn              → which database to send data to
# if_exists='replace' → if table exists, delete and recreate fresh
# index=False       → don't save the Pandas auto-index (0,1,2,3...)
df.to_sql('orders', conn, if_exists='replace', index=False)

print("Database created successfully!")
print("Table 'orders' loaded with", len(df), "rows")

# After this step:
# ecommerce.db is permanently saved on hard drive
# It contains one table called 'orders' with 541,909 rows
# Even if Jupyter closes, the database stays!

Database created successfully!
Table 'orders' loaded with 541909 rows

In [15]:
# ============================================
# STEP 3: Write First SQL Query
# ============================================

# Every SQL query follows this exact pattern:
# 1. Write question in query variable
# 2. Send to database using pd.read_sql_query()
# 3. Result comes back as a DataFrame

# SQL QUERY — Read like plain English:
# SELECT *     → give me ALL columns
# FROM orders  → from the table called orders
# LIMIT 10     → but only show first 10 rows
# NOTE: SELECT never changes data — it only READS
query = """
SELECT *
FROM orders
LIMIT 10
"""

# pd.read_sql_query sends query to database and returns result
# query = the SQL question we wrote above
# conn  = the open door to our database
result = pd.read_sql_query(query, conn)
result    # display result as clean table

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01/12/2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01/12/2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01/12/2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01/12/2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01/12/2010 08:26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,01/12/2010 08:26,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,01/12/2010 08:26,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,01/12/2010 08:28,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,01/12/2010 08:28,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,01/12/2010 08:34,1.69,13047.0,United Kingdom

In [16]:
# ============================================
# QUERY 2 — Count Total Rows In Database
# ============================================

# COUNT(*) counts every single row in the table
# AS total_rows gives the result column a clean name
# This verifies our data loaded correctly
# SQL COUNT(*) = Python len(df) — same idea!
query = """
SELECT 
COUNT(*) AS total_rows
FROM orders
"""
result = pd.read_sql_query(query, conn)
result

   total_rows
0      541909

In [17]:
# ============================================
# QUERY 3 — Find All Unique Countries
# ============================================

# DISTINCT removes duplicate values
# Without DISTINCT → United Kingdom appears thousands of times
# With DISTINCT    → United Kingdom appears only ONCE
# ORDER BY Country → sorts countries A to Z alphabetically
# SQL DISTINCT = Python df['Country'].unique() — same idea!
query = """
SELECT DISTINCT Country
FROM orders
ORDER BY Country
"""
result = pd.read_sql_query(query, conn)

# Show how many unique countries exist
print("Number of countries:", len(result))
result

Number of countries: 38

                 Country
0              Australia
1                Austria
2                Bahrain
3                Belgium
4                 Brazil
5                 Canada
6        Channel Islands
7                 Cyprus
8         Czech Republic
9                Denmark
10                  EIRE
11    European Community
12               Finland
13                France
14               Germany
15                Greece
16             Hong Kong
17               Iceland
18                Israel
19                 Italy
20                 Japan
21               Lebanon
22             Lithuania
23                 Malta
24           Netherlands
25                Norway
26                Poland
27              Portugal
28                   RSA
29          Saudi Arabia
30             Singapore
31                 Spain
32                Sweden
33           Switzerland
34                   USA
35  United Arab Emirates
36        United Kingdom
37           Unspecified

In [18]:
# ============================================
# QUERY 4 — Which Countries Place Most Orders?
# (First Real Business Question!)
# ============================================

# SELECT Country, COUNT(*) → get country name AND
#                            count orders per country
# AS number_of_orders      → give count column a clean name
# GROUP BY Country         → group all rows by country first
#                            then COUNT within each group
#                            SQL GROUP BY = Python df.groupby()
# ORDER BY number_of_orders DESC → sort highest to lowest
#                                  DESC = descending order
# LIMIT 10                 → show only top 10 countries

query = """
SELECT Country, COUNT(*) AS number_of_orders
FROM orders
GROUP BY Country
ORDER BY number_of_orders DESC
LIMIT 10
"""
result = pd.read_sql_query(query, conn)

# Business insight: which markets are most active?
print("Top 10 countries by number of orders:")
result

Top 10 countries by number of orders:

          Country  number_of_orders
0  United Kingdom            495478
1         Germany              9495
2          France              8557
3            EIRE              8196
4           Spain              2533
5     Netherlands              2371
6         Belgium              2069
7     Switzerland              2002
8        Portugal              1519
9       Australia              1259

In [22]:
# ============================================
# QUERY 5 — Filter Rows Using WHERE
# Business Question: Show only UK orders
# ============================================

# WHERE filters rows — like df[df['Country'] == 'UK'] in Pandas
# Only rows where Country exactly matches 'United Kingdom' are returned
# Text values always need single quotes in SQL
# Numbers do NOT need quotes → WHERE Quantity = 6
# WHERE always comes AFTER FROM — order never changes!

# SQL ORDER RULE (never changes):
# SELECT → FROM → WHERE → ORDER BY → LIMIT

query = """
SELECT *
FROM orders
WHERE Country = 'United Kingdom'
LIMIT 10
"""
result = pd.read_sql_query(query, conn)
result

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01/12/2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01/12/2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01/12/2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01/12/2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01/12/2010 08:26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,01/12/2010 08:26,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,01/12/2010 08:26,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,01/12/2010 08:28,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,01/12/2010 08:28,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,01/12/2010 08:34,1.69,13047.0,United Kingdom

In [23]:
# ============================================
# QUERY 6 — WHERE with AND condition
# Business Question: UK customers who bought more than 10 items
# ============================================

# AND means BOTH conditions must be true at the same time
# Condition 1 → Country must be United Kingdom
# Condition 2 → Quantity must be greater than 10
# If either condition is false → that row is excluded

# Comparison operators in SQL:
# >   greater than
# <   less than
# >=  greater than or equal to
# <=  less than or equal to
# =   equal to
# !=  not equal to

# SQL equivalent in Pandas:
# df[(df['Country'] == 'United Kingdom') & (df['Quantity'] > 10)]

# Result: 109,870 rows — 1 in 5 UK orders are bulk purchases!
# Business insight: UK customers frequently buy in bulk

query = """
SELECT *
FROM orders
WHERE Country = 'United Kingdom'
AND Quantity > 10
"""
result = pd.read_sql_query(query, conn)
result

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,01/12/2010 08:34,1.69,13047.0,United Kingdom
1,536371,22086,PAPER CHAIN KIT 50'S CHRISTMAS,80,01/12/2010 09:00,2.55,13748.0,United Kingdom
2,536374,21258,VICTORIAN SEWING BOX LARGE,32,01/12/2010 09:09,10.95,15100.0,United Kingdom
3,536376,22114,HOT WATER BOTTLE TEA AND SYMPATHY,48,01/12/2010 09:32,3.45,15291.0,United Kingdom
4,536376,21733,RED HANGING HEART T-LIGHT HOLDER,64,01/12/2010 09:32,2.55,15291.0,United Kingdom
...,...,...,...,...,...,...,...,...
109865,581585,22398,MAGNETS PACK OF 4 SWALLOWS,12,09/12/2011 12:31,0.39,15804.0,United Kingdom
109866,581585,23145,ZINC T-LIGHT HOLDER STAR LARGE,12,09/12/2011 12:31,0.95,15804.0,United Kingdom
109867,581585,22466,FAIRY TALE COTTAGE NIGHT LIGHT,12,09/12/2011 12:31,1.95,15804.0,United Kingdom
109868,581586,23275,SET OF 3 HANGING OWLS OLLIE BEAK,24,09/12/2011 12:49,1.25,13113.0,United Kingdom
109869,581586,21217,RED RETROSPOT ROUND CAKE TINS,24,09/12/2011 12:49,8.95,13113.0,United Kingdom

In [26]:
# ============================================
# QUERY 7 — WHERE with OR condition
# Business Question: Show orders from UK or Germany
# ============================================

# OR means EITHER condition can be true
# If Country is UK → include the row
# If Country is Germany → include the row
# Both countries end up in the result!

# AND vs OR:
# AND → both must match → fewer results  (more strict)
# OR  → either can match → more results  (more relaxed)

# SQL equivalent in Pandas:
# df[(df['Country'] == 'United Kingdom') | (df['Country'] == 'Germany')]

# Result: 504,973 rows — UK (495,478) + Germany (9,495) combined!

query = """
SELECT *
FROM orders
WHERE Country = 'United Kingdom'
OR Country = 'Germany'
"""
result = pd.read_sql_query(query, conn)
result

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01/12/2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01/12/2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01/12/2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01/12/2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01/12/2010 08:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
504968,581585,22466,FAIRY TALE COTTAGE NIGHT LIGHT,12,09/12/2011 12:31,1.95,15804.0,United Kingdom
504969,581586,22061,LARGE CAKE STAND HANGING STRAWBERY,8,09/12/2011 12:49,2.95,13113.0,United Kingdom
504970,581586,23275,SET OF 3 HANGING OWLS OLLIE BEAK,24,09/12/2011 12:49,1.25,13113.0,United Kingdom
504971,581586,21217,RED RETROSPOT ROUND CAKE TINS,24,09/12/2011 12:49,8.95,13113.0,United Kingdom
504972,581586,20685,DOORMAT RED RETROSPOT,10,09/12/2011 12:49,7.08,13113.0,United Kingdom

In [43]:
# ============================================
# QUERY 8 — Find Rows With Missing CustomerID
# Business Question: Which orders have no customer recorded?
# ============================================

# NULL = missing value in SQL (same as NaN in Pandas)
# GOLDEN RULE: Never use = to check NULL!
# WRONG ❌ → WHERE CustomerID = NULL
# RIGHT ✅ → WHERE CustomerID IS NULL

# IS NULL     → find rows WHERE value IS missing
# IS NOT NULL → find rows WHERE value IS NOT missing

# Result shows CustomerID as None — that is how
# Python displays SQL NULL values

# Notice row 0 → Description is also None AND UnitPrice = 0.00
# Multiple columns missing = serious data quality issue!

# SQL equivalent in Pandas:
# df[df['CustomerID'].isnull()]

query = """
SELECT *
FROM orders
WHERE CustomerID IS NULL
LIMIT 10
"""
result = pd.read_sql_query(query, conn)
result

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536414,22139,None,56,01/12/2010 11:52,0.00,None,United Kingdom
1,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,01/12/2010 14:32,2.51,None,United Kingdom
2,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,01/12/2010 14:32,2.51,None,United Kingdom
3,536544,21786,POLKADOT RAIN HAT,4,01/12/2010 14:32,0.85,None,United Kingdom
4,536544,21787,RAIN PONCHO RETROSPOT,2,01/12/2010 14:32,1.66,None,United Kingdom
5,536544,21790,VINTAGE SNAP CARDS,9,01/12/2010 14:32,1.66,None,United Kingdom
6,536544,21791,VINTAGE HEADS AND TAILS CARD GAME,2,01/12/2010 14:32,2.51,None,United Kingdom
7,536544,21801,CHRISTMAS TREE DECORATION WITH BELL,10,01/12/2010 14:32,0.43,None,United Kingdom
8,536544,21802,CHRISTMAS TREE HEART DECORATION,9,01/12/2010 14:32,0.43,None,United Kingdom
9,536544,21803,CHRISTMAS TREE STAR DECORATION,11,01/12/2010 14:32,0.43,None,United Kingdom

In [42]:
# ============================================
# QUERY 9 — Count Total Missing CustomerIDs
# Business Question: How many orders have no customer recorded?
# ============================================

# Combining COUNT(*) with WHERE IS NULL
# COUNT(*) → counts only the rows that pass the WHERE filter
# No LIMIT needed → COUNT always returns just ONE number

# Result: 135,080 missing out of 541,909 total
# That is 24.9% — nearly 1 in 4 orders has no CustomerID!

# Business Insight:
# These are GUEST ORDERS — customers who bought
# without creating an account
# Must be EXCLUDED from customer-level analysis
# Cannot track, retarget, or analyze these customers

# SQL equivalent in Pandas:
# df['CustomerID'].isnull().sum()

query = """
SELECT COUNT(*) AS missing_customers
FROM orders
WHERE CustomerID IS NULL
"""
result = pd.read_sql_query(query, conn)
result

   missing_customers
0             135080

In [52]:
# ============================================
# QUERY 10 — Count Orders WITH Valid CustomerID
# Business Question: How many orders can we use 
#                    for customer analysis?
# ============================================

# IS NOT NULL → finds rows WHERE value EXISTS (not missing)
# Opposite of IS NULL

# Result: 406,829 valid orders out of 541,909 total
# That is 75.1% — three quarters of orders are trackable!

# Verification check:
# Missing (135,080) + Valid (406,829) = 541,909 total ✅
# Numbers add up perfectly — data is consistent!

# Business Insight:
# Only 406,829 orders can be used for customer analysis
# The remaining 135,080 guest orders must be excluded
# when analyzing customer behavior, loyalty, and churn

# SQL equivalent in Pandas:
# df['CustomerID'].notnull().sum()

query = """
SELECT COUNT(*) AS valid_customers
FROM orders
WHERE CustomerID IS NOT NULL
"""
result = pd.read_sql_query(query, conn)
result

   valid_customers
0           406829