In [1]:
# ============================================
# PROJECT 3 — E-commerce Customer & Sales Analytics
# Dataset: UCI Online Retail (541,909 transactions)
# Tools: Python, SQLite, Pandas, Matplotlib
# ============================================

# Importing required libraries
import pandas as pd      # for data manipulation and reading SQL results
import sqlite3           # for creating and connecting to SQLite database
import os                # for checking files and folders on computer

print("All libraries imported successfully!")
print("sqlite3 version:", sqlite3.sqlite_version)

All libraries imported successfully!
sqlite3 version: 3.51.0

In [2]:
# ============================================
# STEP 1: Load the raw CSV data into Pandas
# ============================================

# read_csv() loads the file into a DataFrame
# encoding='utf-8-sig' removes the hidden BOM character
# that Excel adds when saving CSV files
df = pd.read_csv(
    r'C:\Users\danam\OneDrive\Desktop\ML_journey\project_03_ecommerce_sql\datasets\online_retail.csv',
    encoding='utf-8-sig'
)

# Check what we loaded
print("Shape:", df.shape)           # (rows, columns)
print("\nColumns:", df.columns.tolist())  # all 8 column names
print("\nFirst 5 rows:")
df.head()                           # preview first 5 rows

Shape: (541909, 8)

Columns: ['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']

First 5 rows:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01/12/2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01/12/2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01/12/2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01/12/2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01/12/2010 08:26,3.39,17850.0,United Kingdom

In [3]:
# ============================================
# STEP 2: Create SQLite Database
# ============================================

# sqlite3.connect() does two things:
# → if ecommerce.db does NOT exist: creates it fresh
# → if ecommerce.db already EXISTS: opens it
# conn = the open connection (door) to the database
conn = sqlite3.connect(
    r'C:\Users\danam\OneDrive\Desktop\ML_journey\project_03_ecommerce_sql\datasets\ecommerce.db'
)

# df.to_sql() moves the entire DataFrame into the database
# 'orders'          → name of the table inside the database
# conn              → which database to send data to
# if_exists='replace' → if table exists, delete and recreate fresh
# index=False       → don't save the Pandas auto-index (0,1,2,3...)
df.to_sql('orders', conn, if_exists='replace', index=False)

print("Database created successfully!")
print("Table 'orders' loaded with", len(df), "rows")

# After this step:
# ecommerce.db is permanently saved on hard drive
# It contains one table called 'orders' with 541,909 rows
# Even if Jupyter closes, the database stays!

Database created successfully!
Table 'orders' loaded with 541909 rows

In [4]:
# ============================================
# STEP 3: Write First SQL Query
# ============================================

# Every SQL query follows this exact pattern:
# 1. Write question in query variable
# 2. Send to database using pd.read_sql_query()
# 3. Result comes back as a DataFrame

# SQL QUERY — Read like plain English:
# SELECT *     → give me ALL columns
# FROM orders  → from the table called orders
# LIMIT 10     → but only show first 10 rows
# NOTE: SELECT never changes data — it only READS
query = """
SELECT *
FROM orders
LIMIT 10
"""

# pd.read_sql_query sends query to database and returns result
# query = the SQL question we wrote above
# conn  = the open door to our database
result = pd.read_sql_query(query, conn)
result    # display result as clean table

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01/12/2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01/12/2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01/12/2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01/12/2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01/12/2010 08:26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,01/12/2010 08:26,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,01/12/2010 08:26,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,01/12/2010 08:28,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,01/12/2010 08:28,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,01/12/2010 08:34,1.69,13047.0,United Kingdom

In [5]:
# ============================================
# QUERY 2 — Count Total Rows In Database
# ============================================

# COUNT(*) counts every single row in the table
# AS total_rows gives the result column a clean name
# This verifies our data loaded correctly
# SQL COUNT(*) = Python len(df) — same idea!
query = """
SELECT 
COUNT(*) AS total_rows
FROM orders
"""
result = pd.read_sql_query(query, conn)
result

   total_rows
0      541909

In [9]:
# ============================================
# QUERY 3 — Find All Unique Countries
# ============================================

# DISTINCT removes duplicate values
# Without DISTINCT → United Kingdom appears thousands of times
# With DISTINCT    → United Kingdom appears only ONCE
# ORDER BY Country → sorts countries A to Z alphabetically
# SQL DISTINCT = Python df['Country'].unique() — same idea!
query = """
SELECT DISTINCT Country
FROM orders
ORDER BY Country
"""
result = pd.read_sql_query(query, conn)

# Show how many unique countries exist
print("Number of countries:", len(result))
result

Number of countries: 38

                 Country
0              Australia
1                Austria
2                Bahrain
3                Belgium
4                 Brazil
5                 Canada
6        Channel Islands
7                 Cyprus
8         Czech Republic
9                Denmark
10                  EIRE
11    European Community
12               Finland
13                France
14               Germany
15                Greece
16             Hong Kong
17               Iceland
18                Israel
19                 Italy
20                 Japan
21               Lebanon
22             Lithuania
23                 Malta
24           Netherlands
25                Norway
26                Poland
27              Portugal
28                   RSA
29          Saudi Arabia
30             Singapore
31                 Spain
32                Sweden
33           Switzerland
34                   USA
35  United Arab Emirates
36        United Kingdom
37           Unspecified

In [11]:
# ============================================
# QUERY 4 — Which Countries Place Most Orders?
# (First Real Business Question!)
# ============================================

# SELECT Country, COUNT(*) → get country name AND
#                            count orders per country
# AS number_of_orders      → give count column a clean name
# GROUP BY Country         → group all rows by country first
#                            then COUNT within each group
#                            SQL GROUP BY = Python df.groupby()
# ORDER BY number_of_orders DESC → sort highest to lowest
#                                  DESC = descending order
# LIMIT 10                 → show only top 10 countries

query = """
SELECT Country, COUNT(*) AS number_of_orders
FROM orders
GROUP BY Country
ORDER BY number_of_orders DESC
LIMIT 10
"""
result = pd.read_sql_query(query, conn)

# Business insight: which markets are most active?
print("Top 10 countries by number of orders:")
result

Top 10 countries by number of orders:

          Country  number_of_orders
0  United Kingdom            495478
1         Germany              9495
2          France              8557
3            EIRE              8196
4           Spain              2533
5     Netherlands              2371
6         Belgium              2069
7     Switzerland              2002
8        Portugal              1519
9       Australia              1259