In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
ratings = pd.read_csv(
    r"C:\Users\danam\OneDrive\Desktop\ML_journey\project_02_movie_recommender\datasets\u.data",
    sep='\t',
    names=['user_id', 'movie_id', 'rating', 'timestamp']
)

In [11]:
ratings.head()

   user_id  movie_id  rating  timestamp
0      196       242       3  881250949
1      186       302       3  891717742
2       22       377       1  878887116
3      244        51       2  880606923
4      166       346       1  886397596

In [12]:
ratings.shape

(100000, 4)

In [14]:
movies = pd.read_csv(
    r"C:\Users\danam\OneDrive\Desktop\ML_journey\project_02_movie_recommender\datasets\u.item",
    sep='|',
    encoding='latin-1',
    usecols=[0, 1],
    names=['movie_id', 'title'],
    header=None
)

In [15]:
movies.head()

   movie_id              title
0         1   Toy Story (1995)
1         2   GoldenEye (1995)
2         3  Four Rooms (1995)
3         4  Get Shorty (1995)
4         5     Copycat (1995)

In [17]:
movies.shape

(1682, 2)

In [19]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   user_id    100000 non-null  int64
 1   movie_id   100000 non-null  int64
 2   rating     100000 non-null  int64
 3   timestamp  100000 non-null  int64
dtypes: int64(4)
memory usage: 3.1 MB

In [24]:
ratings.describe()

            user_id       movie_id         rating     timestamp
count  100000.00000  100000.000000  100000.000000  1.000000e+05
mean      462.48475     425.530130       3.529860  8.835289e+08
std       266.61442     330.798356       1.125674  5.343856e+06
min         1.00000       1.000000       1.000000  8.747247e+08
25%       254.00000     175.000000       3.000000  8.794487e+08
50%       447.00000     322.000000       4.000000  8.828269e+08
75%       682.00000     631.000000       4.000000  8.882600e+08
max       943.00000    1682.000000       5.000000  8.932866e+08

In [28]:
df = ratings.merge(movies, on='movie_id')

In [29]:
df.head()

   user_id  movie_id  rating  timestamp                       title
0      196       242       3  881250949                Kolya (1996)
1      186       302       3  891717742    L.A. Confidential (1997)
2       22       377       1  878887116         Heavyweights (1994)
3      244        51       2  880606923  Legends of the Fall (1994)
4      166       346       1  886397596         Jackie Brown (1997)

In [34]:
df.groupby('title')['rating'].count().sort_values(ascending=False)

title
Star Wars (1977)                      583
Contact (1997)                        509
Fargo (1996)                          508
Return of the Jedi (1983)             507
Liar Liar (1997)                      485
                                     ...
Great Day in Harlem, A (1994)           1
Other Voices, Other Rooms (1997)        1
Good Morning (1971)                     1
Girls Town (1996)                       1
Á köldum klaka (Cold Fever) (1994)      1
Name: rating, Length: 1664, dtype: int64

In [35]:
df.groupby('title')['rating'].mean().sort_values(ascending=False)

title
They Made Me a Criminal (1939)                  5.0
Marlene Dietrich: Shadow and Light (1996)       5.0
Saint of Fort Washington, The (1993)            5.0
Someone Else's America (1995)                   5.0
Star Kid (1997)                                 5.0
                                               ...
Eye of Vichy, The (Oeil de Vichy, L') (1993)    1.0
King of New York (1990)                         1.0
Touki Bouki (Journey of the Hyena) (1973)       1.0
Bloody Child, The (1996)                        1.0
Crude Oasis, The (1995)                         1.0
Name: rating, Length: 1664, dtype: float64

In [38]:
movie_stats = df.groupby('title')['rating'].agg(['count', 'mean'])

In [39]:
print(movie_stats)

                                       count      mean
title
'Til There Was You (1997)                  9  2.333333
1-900 (1994)                               5  2.600000
101 Dalmatians (1996)                    109  2.908257
12 Angry Men (1957)                      125  4.344000
187 (1997)                                41  3.024390
...                                      ...       ...
Young Guns II (1990)                      44  2.772727
Young Poisoner's Handbook, The (1995)     41  3.341463
Zeus and Roxanne (1997)                    6  2.166667
unknown                                    9  3.444444
Á köldum klaka (Cold Fever) (1994)         1  3.000000

[1664 rows x 2 columns]

In [41]:
popular_movies = movie_stats[movie_stats['count'] >= 50]

In [43]:
print(popular_movies)

                                     count      mean
title
101 Dalmatians (1996)                  109  2.908257
12 Angry Men (1957)                    125  4.344000
2 Days in the Valley (1996)             93  3.225806
20,000 Leagues Under the Sea (1954)     72  3.500000
2001: A Space Odyssey (1968)           259  3.969112
...                                    ...       ...
Wolf (1994)                             67  2.701493
Wrong Trousers, The (1993)             118  4.466102
Wyatt Earp (1994)                       50  3.100000
Young Frankenstein (1974)              200  3.945000
Young Guns (1988)                      101  3.207921

[605 rows x 2 columns]